### PR TITLE
OE 13356

### PR DESCRIPTION
**Pull request by Tomtids**
Migration to archive this module

### CODE REVIEW

**Comment by Tomtids** [comment]
@biskyt Please review the readme for proposed migration strategy in particular decision not to delete protected files.

**Comment by biskyt** [comment]
@Tomtids - all looks good to me. I'm fine with leaving the protected files in place. If, at a later point we want to clean out orphaned files, then the second approach (in core) would be best anyway. There were quite a few ways where protected files can become orphaned, beyond the scope of the KowaStereo module, so it would make sense to clear them all up at the same time if/when the need arises

**Comment by Tomtids** [comment]
Migration ready for testing against real Kowa stereo data.

**Review by biskyt — APPROVED** [review]

**Comment by biskyt** [comment]
@Tomtids - generally we don't bother leaving FKs on the archive tables, as it just makes them harder to delete later. But not a big enough issue to warrant changes in this PR, just something to keep in mind for the future

**Pull request merged**
